use_frameworks!

target 'LURollingView_Example' do
  pod 'LURollingView', :path => '../'

  target 'LURollingView_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
